# Generated by Django 3.0.9 on 2020-10-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Number', models.CharField(max_length=30)),
                ('Color', models.CharField(max_length=30)),
                ('Device_type', models.CharField(max_length=30)),
                ('Device_Name', models.CharField(max_length=30)),
                ('Manufacture', models.CharField(max_length=30)),
            ],
        ),
    ]
