# Generated by Django 3.0.9 on 2020-10-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustApp', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Employee', models.CharField(max_length=30)),
                ('TypeRepair', models.CharField(max_length=100)),
                ('Completed', models.BooleanField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustApp.Customer')),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustApp.Device')),
            ],
        ),
    ]
