# Generated by Django 3.0.9 on 2020-11-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustApp', '0005_auto_20201109_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
