# Generated by Django 3.0.9 on 2020-11-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustApp', '0006_auto_20201109_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='Customer',
            new_name='CustomerRepair',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='Device',
            new_name='DeviceRepair',
        ),
    ]
