# Generated by Django 3.0.9 on 2020-11-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustApp', '0007_auto_20201109_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='PickedUp',
            field=models.BooleanField(null=True),
        ),
    ]
