# Generated by Django 3.0.9 on 2020-11-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustApp', '0011_auto_20201109_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='pageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_setting_1', models.BooleanField(default=False)),
                ('page_setting_2', models.BooleanField(default=False)),
            ],
        ),
    ]
