# Generated by Django 3.0.9 on 2020-11-12 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CustApp', '0012_pagesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagesettings',
            old_name='page_setting_1',
            new_name='profile_setting_1',
        ),
        migrations.RenameField(
            model_name='pagesettings',
            old_name='page_setting_2',
            new_name='profile_setting_2',
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
