# Generated by Django 3.0.9 on 2020-12-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustApp', '0013_auto_20201112_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(),
        ),
    ]
